# typed: false
# frozen_string_literal: true

# Formula auto-generated by GoReleaser on each release.
# This file lives in the tazi06/homebrew-tap repo under Formula/pipeguard.rb
#
# To create the tap repo:
#   1. Create GitHub repo: tazi06/homebrew-tap
#   2. GoReleaser auto-pushes this formula on `git tag v* && goreleaser release`
#   3. Users install with: brew install tazi06/tap/pipeguard
#
# Manual template below (GoReleaser replaces URLs and checksums automatically):

class Pipeguard < Formula
  desc "Pipeline Security & Quality Scanner — 145 rules, dual scoring, SARIF output"
  homepage "https://github.com/tazi06/pipeguard"
  license "AGPL-3.0"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tazi06/pipeguard/releases/download/v#{version}/pipeguard_#{version}_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"
    else
      url "https://github.com/tazi06/pipeguard/releases/download/v#{version}/pipeguard_#{version}_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/tazi06/pipeguard/releases/download/v#{version}/pipeguard_#{version}_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"
    else
      url "https://github.com/tazi06/pipeguard/releases/download/v#{version}/pipeguard_#{version}_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"
    end
  end

  def install
    bin.install "pipeguard"
  end

  test do
    system "#{bin}/pipeguard", "--version"
  end
end
