# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipeguard < Formula
  desc "Pipeline Security & Quality Scanner — 145 rules, dual scoring, SARIF output"
  homepage "https://github.com/tazi06/pipeguard"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_darwin_amd64.tar.gz"
      sha256 "87c8e3755fd27d7da33ea66c15839a2e62021651cae909fc0c62b7c903b17e78"

      define_method(:install) do
        bin.install "pipeguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_darwin_arm64.tar.gz"
      sha256 "7f1375cc2be51cb523692666a7d3e7739668af246e29f8841ceb7ae6435962cd"

      define_method(:install) do
        bin.install "pipeguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_linux_amd64.tar.gz"
      sha256 "3183e98ddc38e8af2515e4f81f970dc0e9c38d50cae61b53c92038f6f74080ed"
      define_method(:install) do
        bin.install "pipeguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_linux_arm64.tar.gz"
      sha256 "218b3d6081c91938d872ccec950aa81278e25219a4bd2bdb587ca91816431c68"
      define_method(:install) do
        bin.install "pipeguard"
      end
    end
  end

  test do
    system "#{bin}/pipeguard", "--version"
  end
end
