# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipeguard < Formula
  desc "Pipeline Security & Quality Scanner — 145 rules, dual scoring, SARIF output"
  homepage "https://github.com/tazi06/pipeguard"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_darwin_amd64.tar.gz"
      sha256 "47b5090681312a519f514c3de8013f38fe30e6ca67be60d0936ec86dfc5c48ff"

      define_method(:install) do
        bin.install "pipeguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_darwin_arm64.tar.gz"
      sha256 "f4588d92c011148479d0014166c4b92d345ff00f39e2ff175ed70718fcb126ec"

      define_method(:install) do
        bin.install "pipeguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_linux_amd64.tar.gz"
      sha256 "f0c504bb214a4e7dc7e9caf27f01aa451c70f12a577009b52840b58347a4ec61"
      define_method(:install) do
        bin.install "pipeguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_linux_arm64.tar.gz"
      sha256 "23422346f70aa28cd63ff1cf58d9cc4cab546cb0589216f4806aa75d201a5188"
      define_method(:install) do
        bin.install "pipeguard"
      end
    end
  end

  test do
    system "#{bin}/pipeguard", "--version"
  end
end
