# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipeguard < Formula
  desc "Pipeline Security & Quality Scanner — 145 rules, dual scoring, SARIF output"
  homepage "https://github.com/tazi06/pipeguard"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_darwin_amd64.tar.gz"
      sha256 "62a6a20f8fa09f76befc8a97297ac0d17fd0aa0d1de23192c7411164a028cf5d"

      define_method(:install) do
        bin.install "pipeguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_darwin_arm64.tar.gz"
      sha256 "d67808b86a0288758ae7b631a846863b631137d4067ae5114481e62b66c22fab"

      define_method(:install) do
        bin.install "pipeguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_linux_amd64.tar.gz"
      sha256 "570c0393aa5cf2348b61d121a7b2a95ac1c08a13f76b741c04e07de5161ea73c"
      define_method(:install) do
        bin.install "pipeguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tazi06/pipeguard/releases/download/v0.1.0/pipeguard_0.1.0_linux_arm64.tar.gz"
      sha256 "4c7cc42b08012bbe20b8cdc4100742389b1d392703ba6aafb5b3d0714a829d3d"
      define_method(:install) do
        bin.install "pipeguard"
      end
    end
  end

  test do
    system "#{bin}/pipeguard", "--version"
  end
end
